apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-jhyx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-jhyx
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-jhyx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-jhyx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-jhyx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-szrb-tenant/status-quarkus-io/statusquarkusio-jhyx@sha256:eb33a0c614d8291982698200c3b18b4b976764fbd8c7d0215a246bfa2c57c53d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
